### ISSUE TITLE
Cavity.Tests.XmlArrayTest not able to test arrays :p

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eplowe/cavity#1]
```
Think there is a bug in XmlArrayTest where CheckArrayItems uses  
Attribute.GetCustomAttribute instead of  Attribute.GetCustomAttributes

It throws an error if the array has more than one item in

http://code.google.com/p/cavity/source/search?q=XmlArrayTest&origq=XmlArrayTest&
btnG=Search+Trunk

Test 'TowersWatson.Items.Styles.Definition.StylesFacts.prop_HasProperties' 
failed: System.Reflection.AmbiguousMatchException : Multiple custom attributes 
of the same type found.
       at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
       at Cavity.Tests.XmlArrayTest.CheckArrayItems()
       at Cavity.Tests.XmlArrayTest.Check()
       at Cavity.PropertyExpectations`1.<get_Result>b__0(ITestExpectation x)
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
       at Cavity.PropertyExpectations`1.get_Result()
       Items\Styles\Styles.Facts.cs(38,0): at TowersWatson.Items.Styles.Definition.StylesFacts.prop_HasProperties()

Code:

        private void CheckArrayItems()
        {
            var attribute = Attribute.GetCustomAttribute(Member, typeof(XmlArrayItemAttribute), false) as XmlArrayItemAttribute;
            if (null == attribute)
            {
                throw new UnitTestException(string.Format(CultureInfo.InvariantCulture, Resources.XmlArrayDecorationTestException_Message3, Member.Name));
            }

            if (ArrayItemElementName != attribute.ElementName)
            {
                throw new UnitTestException(string.Format(CultureInfo.InvariantCulture, Resources.XmlArrayDecorationTestException_Message4, Member.Name, ArrayItemElementName));
            }
        }



```

Original issue reported on code.google.com by `wa...@prjatk.com` on 28 Mar 2012 at 1:20

**Comment by GoogleCodeExporter** [comment]
```
[XmlArray(...)] issue fixed in build 790.
```

Original comment by `alan.d...@gmail.com` on 1 Apr 2012 at 7:44
- Changed state: **Fixed**
